### ISSUE TITLE
Potentially confusing callback function naming

### ISSUE THREAD

**Issue by OgelGames** [BuckarooBanzay/wield_events#1]
The functions `on_focus` and `on_blur` are not obviously callbacks for when an item is held by a player. Maybe they could be changed to `on_select` and `on_deselect`.

**Comment by BuckarooBanzay** [comment]
i switched to your suggestions, just fyi: i got these names from the javascript callbacks: :smile: 
* https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event
* https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event

i'm developing another (currently private) mod against this and i'm not sure when i'm publishing it (`wield_events`) on the cdb, let me know if you need it...
